villain

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,37 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
+      - name: Checkout master branch
+        uses: actions/checkout@v3
+        with:
+          ref: master
+
+      - name: Merge develop branch into master
+        run: |
+          git fetch origin develop:develop
+          merge_output=$(git merge --no-commit --no-ff develop 2>&1)
+          merge_exit_code=$?
+          echo "::set-output name=merge_output::${merge_output}"
+          exit $merge_exit_code
+
+      - name: Handle merge failure
+        if: ${{ failure() }}
+        run: |
+          merge_output="${{ steps.previous_step.outputs.merge_output }}"
+          echo "Merge failed with the following output:"
+          echo "$merge_output"
+          echo "$merge_output" | grep 'CONFLICT' 
+          curl -X POST https://api.clickup.com/api/v2/list/901804076439/task \
+          -H "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -d '{
+            "name": "Merge Conlfict",
+            "description": "'$merge_output'",
+            "status": "open",
+            "assignees": [90602611],
+          }'
+          exit 0
+
       - name: Create Pull Request
         id: create_pr
         uses: repo-sync/pull-request@v2
@@ -25,8 +56,10 @@ jobs:
             This is an automatically generated pull request to merge changes from `develop` into `master`.
           pr_draft: false
           pr_label: "auto-merge"
+
       - name: OUTPUR PR NUMBER
         run: echo "The PR Number is ${{ steps.create_pr.outputs.pr_number}}"
+
       - name: Create Task in ClickUp with PR Number
         env:
           PR_NUMBER: ${{ steps.create_pr.outputs.pr_number }}
